package elilin.spring.restapp.runner;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertNotNull;

import java.util.Date;

import org.apache.http.HttpResponse;
import org.apache.http.HttpStatus;
import org.junit.AfterClass;
import org.junit.BeforeClass;
import org.junit.Test;


public class MessageServiceTest {
	
	private static WebAppRunner runner;
	
	private JsonRestClient restClient = new JsonRestClient();

	@BeforeClass
	public static void startWebapp() throws Exception {
		runner = new WebAppRunner();
		runner.start();
	}
	
	@AfterClass
	public static void stopWebapp() throws Exception {
		runner.stop();
	}
	
	@Test
	public void postCreatesANewResourceAndReturnsTheUriOfTheNewResourceInTheLocationHeader() throws Exception {
		HttpResponse response = restClient.post(getMessagesUri(), new MessageDto("Hello World!", "Foppa"));
		assertNotNull("Location header should be set", response.getFirstHeader("Location"));
		assertEquals("Status code", HttpStatus.SC_CREATED, response.getStatusLine().getStatusCode());
	}
	
	@Test
	public void getReturnsTheResourceIdentifiedByAGivenUri() throws Exception {
		HttpResponse response = restClient.post(getMessagesUri(), new MessageDto("Hello World!", "Foppa"));
		String messageUri = response.getFirstHeader("Location").getValue();
		
		MessageDto message = restClient.get(messageUri, MessageDto.class);
		assertEquals("Hello World!", message.getMessage());
		assertEquals("Foppa", message.getSignature());
		assertNotNull("Id should be generated by server upon creation", message.getId());
		assertNotNull("Creation time is set by server upon creation", message.getCreated());
	}
	
	@Test
	public void malformedRequestToCreateResourceReturns400StatusCode() throws Exception {
		HttpResponse response = restClient.post(getMessagesUri(), new MessageDto(null, null));
		assertEquals(HttpStatus.SC_BAD_REQUEST, response.getStatusLine().getStatusCode());
	}

	@Test
	public void putUpdatesAnExistingResource() throws Exception {
		HttpResponse response = restClient.post(getMessagesUri(), new MessageDto("Hello World!", "Foppa"));
		
		String messageUri = response.getFirstHeader("Location").getValue();
		MessageDto msg = restClient.get(messageUri, MessageDto.class);
		String etag = restClient.lastResponse().getFirstHeader("ETag").getValue();

		msg.setMessage("Updated message");
		restClient.put(messageUri, msg, etag);
		
		MessageDto updated = restClient.get(messageUri, MessageDto.class);
		
		assertEquals("Updated message", updated.getMessage());
	}

	@Test
	public void deleteRemovesAnExistingMessage() throws Exception {
		HttpResponse response = restClient.post(getMessagesUri(), new MessageDto("Delete me!", "Foppa"));
		String messageUri = response.getFirstHeader("Location").getValue();
		
		response = restClient.delete(messageUri);
		assertEquals(HttpStatus.SC_NO_CONTENT, response.getStatusLine().getStatusCode());
		
		response = restClient.get(messageUri);
		assertEquals(HttpStatus.SC_NOT_FOUND, response.getStatusLine().getStatusCode());
		
		response = restClient.delete(messageUri);
		assertEquals(HttpStatus.SC_NOT_FOUND, response.getStatusLine().getStatusCode());
		
	}

	private String getMessagesUri() {
		return runner.getAbsoluteUrl("/messages");
	}
	
	static class MessageDto {
		
		private Long id;
		private String message;
		private String signature;
		private Date created;
		
		public MessageDto() {}
		
		public MessageDto(String message, String signature) {
			this.message = message;
			this.signature = signature;
		}

		public String getMessage() {
			return message;
		}
		
		public void setMessage(String message) {
			this.message = message;
		}
		
		public String getSignature() {
			return signature;
		}
		
		public void setSignature(String signature) {
			this.signature = signature;
		}

		public Long getId() {
			return id;
		}

		public void setId(Long id) {
			this.id = id;
		}

		public Date getCreated() {
			return created;
		}

		public void setCreated(Date created) {
			this.created = created;
		}
		
	}
	
}
